export const DUMMY_DATA = [
    {
        name: "Parking Lot 01",
        latitude: 31.243873,
        longitude: 34.793990,
        parking_spots: 10,
        freeSpots: 10,
        parkings: [
            { id: 1, occupied: false, license_number: null },
            { id: 2, occupied: false, license_number: null },
            { id: 3, occupied: false, license_number: null },
            { id: 4, occupied: false, license_number: null },
            { id: 5, occupied: false, license_number: null },
            { id: 6, occupied: false, license_number: null },
            { id: 7, occupied: false, license_number: null },
            { id: 8, occupied: false, license_number: null },
            { id: 9, occupied: false, license_number: null },
            { id: 10, occupied: false, license_number: null },
        ],
    },
    {
        name: "Parking Lot 02",
        latitude: 31.245678,
        longitude: 34.795678,
        parking_spots: 12,
        freeSpots: 9,
        parkings: [
            { id: 1, occupied: false, license_number: null },
            { id: 2, occupied: false, license_number: null },
            { id: 3, occupied: true, license_number: "123-45-678" },
            { id: 4, occupied: true, license_number: "876-54-321" },
            { id: 5, occupied: true, license_number: "555-66-777" },
            { id: 6, occupied: false, license_number: null },
            { id: 7, occupied: false, license_number: null },
            { id: 8, occupied: true, license_number: "222-33-444" },
            { id: 9, occupied: false, license_number: null },
            { id: 10, occupied: false, license_number: null },
            { id: 11, occupied: false, license_number: null },
            { id: 12, occupied: false, license_number: null },
        ],
    },
    {
        name: "Parking Lot 03",
        latitude: 31.247890,
        longitude: 34.797890,
        parking_spots: 15,
        freeSpots: 12,
        parkings: [
            { id: 1, occupied: true, license_number: "100-11-200" },
            { id: 2, occupied: false, license_number: null },
            { id: 3, occupied: false, license_number: null },
            { id: 4, occupied: false, license_number: null },
            { id: 5, occupied: false, license_number: null },
            { id: 6, occupied: true, license_number: "999-88-777" },
            { id: 7, occupied: false, license_number: null },
            { id: 8, occupied: false, license_number: null },
            { id: 9, occupied: false, license_number: null },
            { id: 10, occupied: true, license_number: "333-22-111" },
            { id: 11, occupied: false, license_number: null },
            { id: 12, occupied: false, license_number: null },
            { id: 13, occupied: false, license_number: null },
            { id: 14, occupied: false, license_number: null },
            { id: 15, occupied: false, license_number: null },
        ],
    },
    {
        name: "Parking Lot 04",
        latitude: 31.249012,
        longitude: 34.799012,
        parking_spots: 8,
        freeSpots: 1,
        parkings: [
            { id: 1, occupied: true, license_number: "444-44-444" },
            { id: 2, occupied: true, license_number: "333-33-333" },
            { id: 3, occupied: true, license_number: "222-22-222" },
            { id: 4, occupied: true, license_number: "111-11-111" },
            { id: 5, occupied: true, license_number: "555-55-555" },
            { id: 6, occupied: true, license_number: "666-66-666" },
            { id: 7, occupied: true, license_number: "777-77-777" },
            { id: 8, occupied: false, license_number: null },
        ],
    },
    {
        name: "Parking Lot 05",
        latitude: 31.241234,
        longitude: 34.791234,
        parking_spots: 21,
        freeSpots: 13,
        parkings: [
            { id: 1, occupied: false, license_number: null },
            { id: 2, occupied: false, license_number: null },
            { id: 3, occupied: true, license_number: "123-45-678" },
            { id: 4, occupied: true, license_number: "876-54-321" },
            { id: 5, occupied: true, license_number: "555-66-777" },
            { id: 6, occupied: false, license_number: null },
            { id: 7, occupied: false, license_number: null },
            { id: 8, occupied: false, license_number: null },
            { id: 9, occupied: false, license_number: null },
            { id: 10, occupied: true, license_number: "222-33-444" },
            { id: 11, occupied: false, license_number: null },
            { id: 12, occupied: false, license_number: null },
            { id: 13, occupied: false, license_number: null },
            { id: 14, occupied: false, license_number: null },
            { id: 15, occupied: false, license_number: null },
            { id: 16, occupied: false, license_number: null },
            { id: 17, occupied: false, license_number: null },
            { id: 18, occupied: false, license_number: null },
            { id: 19, occupied: false, license_number: null },
            { id: 20, occupied: true, license_number: "999-88-777" },
            { id: 21, occupied: false, license_number: null },
        ],
    },
];
